SET(ROGII_GOOGLETEST_MAJOR_VERSION 1)
SET(ROGII_GOOGLETEST_MINOR_VERSION 11)
SET(ROGII_GOOGLETEST_PATCH_VERSION 0)

SET(ROGII_GOOGLETEST_VERSION ${ROGII_GOOGLETEST_MAJOR_VERSION}.${ROGII_GOOGLETEST_MINOR_VERSION}.${ROGII_GOOGLETEST_PATCH_VERSION})
